### ISSUE TITLE
QST hangs on launch when starting syncthing-inotify

### ISSUE THREAD

**Issue by stevenbagley** [sieren/QSyncthingTray#103]
Symptom: QST hangs on launch (by hand or using login items) with spinning beachball, and never returns. It does start syncthing, though. This only happens if launch inotify is selected in QST preferences. If inotify is already running, or launched using LaunchAgents, everything is fine.

Mac OS X 10.11.4, syncthing v0.12.21, syncthing-inotify v0.6.8, QST version 0.4.4 (from downloaded binary). Syncthing and syncthing-inotify installed using homebrew.

**Comment by sieren** [comment]
Interesting, this seems to happen only with the downloaded version. I'll investigate further, presumable it has something to do with app-signing.

**Comment by sieren** [comment]
I had a closer look at this, but still not clear why exactly this happens.
Can you check out if this build works for you?
https://www.dropbox.com/s/spqnku28489u5eg/QSyncthingTray.dmg?dl=0

**Comment by stevenbagley** [comment]
Yes, that build appears to solve the problem. Thanks.

**Comment by sieren** [comment]
Great, thanks for your feedback
