### ISSUE TITLE
Crashes KDE Plasma 5

### ISSUE THREAD

**Issue by computerfr33k** [sieren/QSyncthingTray#106]
When running for a while on Arch Linux, this program will eventually cause KDE Plasma 5 to crash. This does not happen when I run Syncthing-GTK. Not sure why it is that this application causes KDE to crash though.

**Comment by computerfr33k** [comment]
I think there is a really bad memory leak somewhere because after a little while All of my RAM was filled up and the only thing available was my swap space causing my system to respond extremely slowly.

**Comment by sieren** [comment]
Thanks, I'll look into it

**Comment by sieren** [comment]
Seems specific to KDE. I was able to observe growing memory on Ubuntu Neon, but unfortunately Valgrind kept on crashing so I havent been able to identify the issue just yet.
Will look into this further.

**Comment by computerfr33k** [comment]
Is there any KDE integrations being used that might cause something to leak?

On May 8, 2016 11:32:59 AM CDT, Matt Sieren <notifications@github.com> wrote:
>Seems specific to KDE. I was able to observe growing memory on Ubuntu
>Neon, but unfortunately Valgrind kept on crashing so I havent been able
>to identify the issue just yet.
>Will look into this further.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sieren/QSyncthingTray/issues/106#issuecomment-217731223

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sieren** [comment]
Not from my end. However Qt does almost certainly behave differently under KDE, so I'm guessing it shows an error in my code which on other platforms didn't surface.

**Comment by sieren** [comment]
However, there is some correlation between Qt and KDE Leaks, specifically when it comes to applications with a tray icon:
https://bugs.kde.org/show_bug.cgi?id=344879

**Comment by sieren** [comment]
I've found the issue. QST calls "setIcon" on every connection update, which seems to be causing memory leaks within Qt:
https://bugreports.qt.io/browse/QTBUG-16113?jql=text%20~%20%22setIcon%20memory%22
https://bugreports.qt.io/browse/QTBUG-26263?jql=text%20~%20%22setIcon%20memory%22
https://bugreports.qt.io/browse/QTBUG-23658?jql=text%20~%20%22setIcon%20memory%22

I've deployed a workaround for the next version.

**Comment by computerfr33k** [comment]
Seems to be working a lot better now.

**Comment by sieren** [comment]
@computerfr33k the issue come up again at https://github.com/sieren/QSyncthingTray/issues/123 .. how are the recent fixes working out for you? did the problem resurface? Trying to track this one down once and for all, but seems tricky. Maybe you got some additional input to post over there?

**Comment by computerfr33k** [comment]
It has been fine for me, I am not using the animated icon. I am running it on Arch so maybe he's running a different version of Qt/KDE/QST.
