### ISSUE TITLE
QSyncthingTray cause high CPU usage on OS X

### ISSUE THREAD

**Issue by gadric** [sieren/QSyncthingTray#109]
Hi, 

I just downloaded and installed the new version QSyncthingTray for OS X. I am using the newest version of syncthing and syncthing-inotify. However, the new version of QSyncthingTray causes high CPU load (around 100%) on my MacBook Air, which wasn't the case with the previous version. Also, syncthing has a hight CPU load together with QSyncthingTray. When I start syncthing and syncthing-inotify without QSyncthingTray, they works fine. 

Can you fix this problem? Please let me know if you need more infos from my side!

**Comment by sieren** [comment]
Oh, I have an idea as to what might cause this. Can you go to preferences and check the polling-interval setting? (and maybe set it to some other value?).

**Comment by gadric** [comment]
Thanks for the quick answer. The polling-interval is on 0

**Comment by sieren** [comment]
Just tried it out myself, it is in fact the issue. Setting it to a different value resolves it.
Seems like I need a more version-dependent way to handle changes in the Settings document. I'll think of something and push/release a new version tonight.

**Comment by gadric** [comment]
Thanks. This resolved the problem (but QSyncthingTray needs to be restarted). What does the value do?

**Comment by sieren** [comment]
QST speaks with Syncthing over the HTTP API.
It specifies how often it should ask for an update. 0 obviously makes it ask as fast as it can.
A good default value is 1 or 2.

**Comment by gadric** [comment]
ah ok. I set it on 10 :) now the cpu usage issues are gone.

**Comment by sieren** [comment]
Thanks for the quick reply!
I've just deployed an update with a preliminary fix. I'll get this right some other time, but this should do it for now :)
