### ISSUE TITLE
QSyncthing Interface doesn't show [Syncthing v0.12.24]

### ISSUE THREAD

**Issue by computerfr33k** [sieren/QSyncthingTray#111]
Here's a screenshot
![screenshot_20160517_154435](https://cloud.githubusercontent.com/assets/2096910/15338678/8d540470-1c46-11e6-9b5b-14e44a3b2308.png)

**Comment by leprechau** [comment]
Same here.  Synching 0.12.24 installed via brew and QSyncthingTray 0.4.6 via the DMG on the releases tab on OS X El Capitan (10.11.5)

<img width="804" alt="screenshot 2016-05-17 19 02 11" src="https://cloud.githubusercontent.com/assets/1444686/15343391/e04dc88a-1c61-11e6-8876-d9049ec4eb98.png">

**Comment by meztup** [comment]
Same here, but Syncthing 0.13.0 on Win7 x64.
![untitled](https://cloud.githubusercontent.com/assets/16569239/15347997/50b44f84-1c8c-11e6-8556-0d49e750879b.png)

**Comment by sieren** [comment]
Thanks for the reply! I've put out another bugfix release: 
https://github.com/sieren/QSyncthingTray/releases/tag/0.4.7

The next one will probably come with an overhaul of the whole connection logic, to avoid those mistakes altogether.

**Comment by leprechau** [comment]
Thank you!

**Comment by meztup** [comment]
Confirmed fixed on Win 7 x64 as well!
