### ISSUE TITLE
All lines in tray menu look clickable (OSX)

### ISSUE THREAD

**Issue by erikvanoosten** [sieren/QSyncthingTray#114]
On OSX all lines of the tray menu look clickable while some have no action associated with them. Please make the text of lines without an action gray so to that they appear non-clickable.

**Comment by leprechau** [comment]
They are all clickable ...

Pause Syncthing pauses thinghing
Open Syncthing opens the builtin webui
Preferences opens the preferences window
About opens the about page
Quit quits

What else would you want?
  
<img width="150" alt="screenshot 2016-05-21 12 46 58" src="https://cloud.githubusercontent.com/assets/1444686/15449941/20edefd0-1f52-11e6-9905-39e27d2071f6.png">

**Comment by erikvanoosten** [comment]
If it _is_ connected, the menu also shows throughput numbers in black. However, I have not been able to see such numbers since the last upgrade to Syncthing 0.13.

**Comment by leprechau** [comment]
Check out #115 for a workaround to get the tray icon connected to synching 0.13.2

**Comment by sieren** [comment]
Confirmed this is an issue with v13. Will look into it next week!
