### ISSUE TITLE
QSyncthingTray quits after wake up from hibernate (OS X)

### ISSUE THREAD

**Issue by gadric** [sieren/QSyncthingTray#119]
Hi, 

QSyncthingTray (0.47) seems to quit after wake up from hibernate mode in Mac OS X (El Capitan, 10.11.5). Also, QSyncthingTray-inotify seems not running after wake up. But syncthing (13.2) itself keeps running. 

any idea?

**Comment by sieren** [comment]
This is possibily related to https://github.com/sieren/QSyncthingTray/issues/115 which breaks QST right now.

**Comment by sieren** [comment]
Quick update, thats a crash which is fixed in https://github.com/sieren/QSyncthingTray/pull/121 and in the next version.

**Comment by sieren** [comment]
Let me know how this works for you:
https://github.com/sieren/QSyncthingTray/releases/tag/0.5.0
