### ISSUE TITLE
Rename without the Q ?

### ISSUE THREAD

**Issue by MoOx** [sieren/QSyncthingTray#12]
I know why the Q is in the name, but in terms of UX, I thing a simpler name like "Syncthing Tray" is a better idea. Don't you think ?

**Comment by sieren** [comment]
I agree. I will consider and advise with the devs of Syncthing whether this is okay (since it sounds rather official) :)

**Comment by calmh** [comment]
I'm fine with it either way. :) The Q being a technical detail I can agree it might be better off without it. There are already multiple "tray things" and I think any confusion between them needs to be sorted out on the download site and so on anyway.

**Comment by sieren** [comment]
Hard to tell on how to proceed on this as there's a few ones around already as @calmh rightfully pointed out.
E.g. https://github.com/alex2108/syncthing-tray

I'm open for names though and agree the "Q" might cause more confusion than additional value in terms of UX.

**Comment by meztup** [comment]
Meh. The "Q" is growing on me. Maybe "Syncthing QTray"? Which isn't any more or less clever than the original name is, btw...

**Comment by sieren** [comment]
I think I'll leave it with QSyncthingTray for now... since people even have come up with the abbreviation QST already :)
