### ISSUE TITLE
If Font Awesome not installed on system, the icons are not showing

### ISSUE THREAD

**Issue by Getron** [sieren/QSyncthingTray#120]
I have yesterday fresh installed my system, Netrunner Rolling 2016.01, an Arch and Manjaro rolling release, and installed the QSyncthingTray, but, the icons are not showing on GUI Window.

After i manually installed the Font Awesome with Octopi Software Manager (an Arch Pacman GUI Software Manager), the icons are showing like it should be on the GUI Window of QSynthingTray.

Font Awesome should somehow be included on this app, if possible, for people who doesn't known how Syncthing works, and what for Font are needed. I'm myself long time with Synthing on Git, and therefore, i known the issue, why the icons are not showed on a fresh installed PC -because font Awesome is missing.

**Comment by sieren** [comment]
It seems like that's an issue coming out of Syncthing?
QSyncthingTray is using the Qt framework which in return is using native System Fonts to display anything UI related (other than the Web-UI of Syncthing itself - where in fact font-awesome seems to be a part of it: https://github.com/syncthing/syncthing/tree/master/gui/default/vendor/font-awesome )

**Comment by Getron** [comment]
@sieren i don't known, but, on my fresh installed system, it has not worked, the font icons are not showed until i have installed it manually on my system. After manually installed the font, the icons are showed like it should be.

Maybe you try it on Virtual Machine, on Virtualbox, on fresh installed system, and you see the problem there.

Thanks

**Comment by sieren** [comment]
I assume you installed the Arch package of QST?
I'd recommend addressing this over here: https://aur.archlinux.org/packages/qsyncthingtray/ and suggesting to add Font Awesome as a dependency.
