### ISSUE TITLE
Migrate QST Config to new company identifier

### ISSUE THREAD

**Issue by sieren** [sieren/QSyncthingTray#125]
Issue raised here: https://github.com/sieren/QSyncthingTray/issues/123#issuecomment-222558881

The (Qt)-Company identifier for settings is `sieren` which is confusing when you want to locate the config file (esp. on Linux).
This should become `QST` or `QSyncthingTray` but would require some additional work to migrate existing configuration files to the new one.

**Comment by Getron** [comment]
@sieren it is this done on the new v0.5.1?

If yes, easy way is, to maybe uninstall, and reinstall it do the new location?

**Comment by Getron** [comment]
@sieren i have uninstalled it, deleted the sieren folder from .config folder on my Linux, installed it again, but, it keeps doing the same "sieren" folder.

Maybe you change it for new installations, should crate a QST or QSyncthingTray named folder, i think, it is the best one way to create this under the .config/Syncthing/QSyncthingTray folder.

Like this, it is very easy to find it, and it has to do with Syncthing, all people search it on this Syncthing folder, and not separately.

If the Syncthing is not installed on local machine, the QSyncthingTray should create this Syncthing/QSyncthingTray folder under the .config folder on Linux.

This is my proposal, if it is doable?
Thanks

**Comment by sieren** [comment]
Hey,

no, this hasnt been done yet. Presumably in the next version.
Thanks for your input though, I'll consider it once I get to it.

**Comment by sieren** [comment]
There's a PR in place now to fix this:
https://github.com/sieren/QSyncthingTray/pull/144
