### ISSUE TITLE
0.5.1 for OSX is damaged

### ISSUE THREAD

**Issue by achekulaev** [sieren/QSyncthingTray#126]
While 0.5.0 is fine
https://dl.dropbox.com/s/i9v24yaty1jxmpo/screencast_2016-05-31_16-30-26.mp4?dl=0

**Comment by sieren** [comment]
Ah, damnit! I really should mark more stuff as pre-release. Maintaining 3 platforms (+2 linux distros) isnt as easy as I've thought.
Anyway, I have a clue, this is likely related to https://github.com/sieren/QSyncthingTray/pull/124 and caused by the new repo organisation. I'll fix it in the next few days and post an update here.

**Comment by sieren** [comment]
Thanks for the report.

**Comment by achekulaev** [comment]
Update: it's not completely damaged. I should have had copied it over previous version or something and it created a problem I'm not sure why it did not start before. But now it starts. But looks quirky

0.5.1 
https://dl.dropbox.com/s/81ju60oy2nd4tws/Monosnap_2016-05-31_16-40-30.png?dl=0

0.5.0
https://dl.dropbox.com/s/3e4mqc7p9qqe3gb/Monosnap_2016-05-31_16-41-20.png?dl=0

**Comment by sieren** [comment]
Already deployed a fix and uploading as we speak ;)

**Comment by achekulaev** [comment]
Thanks :)

**Comment by sieren** [comment]
Here we go:
https://github.com/sieren/QSyncthingTray/releases/tag/0.5.1r2

Let me know if that works out for you

**Comment by achekulaev** [comment]
Yes. Now the icon and font looks just fine and App works. 

On the problem that existed before. I guess I should notify you about it although it's not the application problem. But I guess something could possibly be done on the application side to avoid it. Or maybe it can be documented.

In case when 'Security and Privacy' setting is set to 'Mac App Store and indentified developers' the app will not run of course. And that's fine. 

However if user goes to that dialog and presses 'Open anyway' button (like here http://cdn.osxdaily.com/wp-content/uploads/2013/11/bypass-gatekeeper-os-x.jpg) then OSX will start application but with QST it starts it in some weird way. So that it will end up thinking it's broken. Just like on video or on this screenshot https://dl.dropbox.com/s/p3lzn5pgfkmx54i/Monosnap_2016-05-31_16-50-32.png?dl=0

However if I change setting to 'Anywhere' then QSyncthingTray will work just fine. 

For some users company policy may prevent from checking that option.

**Comment by sieren** [comment]
Yeah, I'm aware of this. I need to properly sign the application eventually. Still need to figure out a way to do that without completely breaking my current workflow.
