### ISSUE TITLE
Restarting QST kills syncthing process

### ISSUE THREAD

**Issue by stevenbagley** [sieren/QSyncthingTray#128]
With syncthing and QST running, quit QST, then restart QST; the last operation kills the running syncthing process. In QST preferences, none of Launch Syncthing, Shutdown on Exit, or Launch iNotify are selected. Syncthing and syncthing-inotify are both installed using homebrew and launched by LaunchAgents, QST is started the first time using Login items.

Mac OS X 10.11.5, with syncthing v0.13.4 and QST 0.5.1r2

**Comment by sieren** [comment]
Thanks, deployed a fix for the next release.
