### ISSUE TITLE
QST loses setting of Notifications preference

### ISSUE THREAD

**Issue by stevenbagley** [sieren/QSyncthingTray#129]
Notifications is selected (by default). Unselect, then restart QST. Notifications is now selected again.

Mac OS X 10.11.5, with syncthing v0.13.4 and QST 0.5.1r2

**Comment by sieren** [comment]
Thanks, deployed a fix for the next release.

**Comment by es20490446e** [comment]
Still there:
https://github.com/sieren/QSyncthingTray/issues/238
