### ISSUE TITLE
QST always says "Not Connected" regardless of actual status

### ISSUE THREAD

**Issue by DarwinAwardWinner** [sieren/QSyncthingTray#130]
Title says it all, really. For the past week or two, the tray icon has been grayed out and the status has said "Not Connected". However, everything continues to function, Syncthing keeps syncing, etc.

**Comment by sieren** [comment]
Can you add which version you are using?

**Comment by DarwinAwardWinner** [comment]
Syncthing v0.13.4
QST v0.4.2

**Comment by sieren** [comment]
Can you try and give me feedback on a newer version? 
0.4.2 doesnt work properly with Syncthing v13.. I recommend getting 0.5.1

**Comment by DarwinAwardWinner** [comment]
Seems to be fixed in 0.5.1. Thanks for your help!
