### ISSUE TITLE
size of binary OSX 133 MB

### ISSUE THREAD

**Issue by uglygus** [sieren/QSyncthingTray#133]
The size of the binary (133MB) is very large for such a minimal application. I see a few frameworks right off the bat that seem likely to be unnecessary.

Print support (308k) is not used as far as I can tell. Maybe it has internal dependancies?
Web support (94MB) why not just rely on the default web browser? Bundling your own web browser to show one page seems like overkill. 

QSyncthingTray.app
    Content
        Frameworks
             QtPrintSupport.framework (308k)
             QtWebChannel.framework (147k)
             QtWebEngine.framework (295k)
             QtWebEngineCore.framework (93.1MB)
             QtWebEngineWidgets.framework (238k)

**Comment by sieren** [comment]
Yeah, I'm aware and this comes up every now and then. I'd like to get some more input from other users when it comes to convenience vs. filesize before removing this feature/framework.

**Comment by sieren** [comment]
Deferred to: https://github.com/sieren/QSyncthingTray/issues/138
