### ISSUE TITLE
How do you build this using a distribution packaged qt5?

### ISSUE THREAD

**Issue by vext01** [sieren/QSyncthingTray#135]
Hi,

I'm using qt5-5.5.1 via OpenBSD packages. The headers are in `/usr/local/include/X11/qt5` and the libs are in `/usr/local/lib/qt5`.

As far as I can see, your code expects all of QT to be installed in one place QTDIR. Is this an oversight?

**Comment by sieren** [comment]
Not really.. QTDIR should point to the Cmake Files of Qt itself (e.g. `/usr/lib/x86_64-linux-gnu`)

**Comment by vext01** [comment]
To follow this up, QtWebEngine is not yet ported to OpenBSD, so I didn't get as far as getting a build. I was unable to find a QTDIR which correctly detected qt5 cmake modules either. I instead fell back on manually specifying paths like this:

```
env Qt5Widgets_DIR=/usr/local/lib/qt5/cmake/Qt5Widgets  cmake ..
```

**Comment by sieren** [comment]
Mhmm.. interesting. Would it help to add conditionals and remove the QtWebEngine dependency for OpenBSD builds?

**Comment by vext01** [comment]
If it isnt a great deal of effort, certainly.

**Comment by vext01** [comment]
Is this `-DQST_BUILD_WEBKIT=1`?

**Comment by sieren** [comment]
That removes the QtWebEngine dependency, yeah.
The discussion about this had moved here back then:
https://github.com/sieren/QSyncthingTray/issues/145

**Comment by vext01** [comment]
Right, I have a compilation issue with this flag turned on -- will raise an issue.
