### ISSUE TITLE
Spotlight does not find QSyncthingTray

### ISSUE THREAD

**Issue by gadric** [sieren/QSyncthingTray#136]
I realised that Spotlight on Mac OS X (El Capitan 10.11.4) does not find QSyncthingTray in the Applications folders. Is this a local issue on my machine?

**Comment by sieren** [comment]
Same happens here. I assume this is due to the lack of the app being code-signed. I'll fix that in the future

**Comment by gadric** [comment]
Btw.: Windows 8.1 does not find QSyncthingTray either.

**Comment by sieren** [comment]
@gadric adresses this (on OSX) in https://github.com/sieren/QSyncthingTray/issues/139

I'll look into Windows next.
