### ISSUE TITLE
Retina issue?

### ISSUE THREAD

**Issue by calmh** [sieren/QSyncthingTray#137]
0.5.1r2, starts browser like this:

<img width="1392" alt="screen shot 2016-06-18 at 23 44 48" src="https://cloud.githubusercontent.com/assets/125426/16173858/bfc3e804-35ae-11e6-9a0a-aefdb3b486d9.png">

Latest El Capitan, no known funky business.

**Comment by sieren** [comment]
Interesting, I'll look into it. That should not happen.

**Comment by sieren** [comment]
Hey @calmh ,

I tried to reproduce this but to no avail. Can you go to QST Preferences and check if the Scaling Factor is set to 1.0 ?

<img width="1536" alt="screen shot 2016-07-09 at 11 09 43" src="https://cloud.githubusercontent.com/assets/5174440/16707151/b3153fb4-45c5-11e6-8fdf-8ebf234b32f5.png">
