### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ech1965** [sieren/QSyncthingTray#14]
Another Tray Application for Syncthing [1] has a very useful feature worth "stealing" ;-)

Pause synching when it detects certains applications running. 

EG: I sync my Lightroom catalogs with syncthing and it's really usefull to have syncthing pause itselfs automatically when lightroom starts. It prevents my lightroom catalog being hosed by the sync process.

[1] https://github.com/m0ppers/syncthing-bar

**Comment by sieren** [comment]
Ah cool, havent thought of that. 
Shouldnt be too hard to implement, can you elaborate how this is handled in the other app (purely from a User experience perspective) ?

**Comment by ech1965** [comment]
In the settings dialog box, there is an text box where you can enumerate the list of Applications ( comma separated) you want the tray app to watch for.

Pretty simple but efficient

**Comment by sieren** [comment]
Started taking this up, but will ultimately go with a proper Table instead of a comma-seperated list.
Hope I to add this in the forthcoming 0.2.5 release.

**Comment by ech1965** [comment]
Awsome !!!

**Comment by sieren** [comment]
Sorry for the noise in here.. 
If you have some time, give this a try and let me know if it works :)

https://github.com/sieren/QSyncthingTray/releases/tag/0.2.5

**Comment by ech1965** [comment]
Quite busy these days, but I'll test it... thanks

**Comment by ech1965** [comment]
Sorry to the late feedback..

How can I discover the value I have to configure in QSynthingTray to let it pause ?

I want to pause QSyncthingTray when Adobe Lightroom is running. (On OSX )

I tried "Adobe Lightroom"  (Name of the .app Directory) btw also the name of the executable.
I tried "/Applications/Adobe Lightroom/Adobe Lightroom.app/Contents/MacOS/Adobe Lightroom", the full path of the executable, but I'm still seing icon animation and traffic stats non zero even if Lightroom is Running

Thanks for your feedback

**Comment by sieren** [comment]
Can you try entering "Adobe Lightroom" (including the apostrophes) ?
I discovered a potential issue with white-spaces in app names

**Comment by sieren** [comment]
Deployed a fix for 0.4.4 - for now I recommend adding apostrophes for app-names with whitespaces when adding a process to the list.
