### ISSUE TITLE
OSX Attempts to use authentication when checkbox is unchecked

### ISSUE THREAD

**Issue by opie4624** [sieren/QSyncthingTray#140]
Error message: `Status: Error downloading http://:@127.0.0.1:8384` 

v0.4.7 from Homebrew Cask on OSX 10.11.5

SyncThing v0.13.10 from Homebrew

**Comment by sieren** [comment]
0.4.7 and v13 are broken - please try a newer version (0.5.1r2)  - https://github.com/sieren/QSyncthingTray/releases/tag/0.5.1r2

**Comment by opie4624** [comment]
Newest version fixes the issue.

Updated Cask: caskroom/homebrew-cask#22728

Thanks for the quick response.

**Comment by sieren** [comment]
Thanks for the Cask update 👍
