### ISSUE TITLE
Use black window background with dark theme

### ISSUE THREAD

**Issue by AloisMahdal** [sieren/QSyncthingTray#151]
I'm not sure if this is doable, but it would be nice if QSyncthingTray would recognize that dark theme is set and when initializing window, would use dark background color from start.

Currently, the window is white when opening, so it really limits usability of the black theme (IOW, hurts my eyes).

I imagine few approaches to this problem; some of them might not be possible:

 *  Really recognize the option and force color.

    This is most straightforward and fully effective, but relies on ability to read and understand
    syncthing config, including recognizing "dark "and "light" themes.

 *  Don't show the window unless fully loaded.

    Solves the issue but at the prize of slower response, which could be problem
    with remote syncthing instances, or in case of syncthing web UI bug (the UI might
    even never load or trigger the "loaded" event)

 *  Remember last background color set by HTML and restore it.

    This removes the problem of syncthing config and dark/light, but only affects second
    and further window opening after theme change (unless the color would be remembered
    through restarts).

 *  just give user configuation option to use dark color (any color or just "dark" checkbox).

    Probably the simplest, although requires extra step for user.

 *  Just use dark color. Always.

    No, this one is the simplest ;)

**Comment by sieren** [comment]
Hey, can you elaborate a bit? Since QST is cross-platform, best is to illustrate with screenshots :)
Stuff like this boils down to Qt's integration with the platform itself, not sure if this is possible but I can definitely look into it once I have some more details. Or maybe someone else wants to pick this up for once? :-)

**Comment by AloisMahdal** [comment]
The problem is that even though I use dark theme, my eyes still get hurt when opening the QST window, because during the few seconds until it loads, the window is white.

I recorded a video of the effect:

    http://file.vornet.cz/tmp/qts-white.ogv

Above is list of suggestions in terms of behavior; I'm not aware of details of QT capabilities, I realize some (or even all) solutions could be tricky or even impossible ATM.

**Comment by sieren** [comment]
This might be tricky. I don't want to introduce a dark theme mode just for a flashing background, that'd just confuse users. I'll think of something though. On OSX you get a grey background for less than a second before it loads. I'll see if I can use some kind of grey color as a compromise between light and dark.

**Comment by sieren** [comment]
WebView will initialize with dark-gray background in next release.

**Comment by AloisMahdal** [comment]
Thanks, it looks much better now!
