### ISSUE TITLE
Show/hide (not just show/reload) window when clicking tray icon

### ISSUE THREAD

**Issue by AloisMahdal** [sieren/QSyncthingTray#152]
I believe the common behavior (hexchat, clementine, psi, claws-mail, opera...) of tray icons on clicking is to toggle (show/hide) window presence rather than show the window and re-load it on consecutive clicks (which is how QSyncthingTray behaves now).

So accodiing to least-surprise principle, it would be nice to have QSyncthingTray behave like that as well.

**Comment by sieren** [comment]
do you mean single or double click?

**Comment by AloisMahdal** [comment]
I mean single click

**Comment by AloisMahdal** [comment]
(darn that close&comment button is so huge :))

**Comment by sieren** [comment]
Opened a new branch and will get this fixed ;)

**Comment by sieren** [comment]
Alright. Merging a fix which makes sure that the Window gets raised to foreground if its already active, else it gets reinstantiated. This is kind of a tradeoff between toggling between show/hide and I suppose it makes more sense to close the window through the window manager and not the icon itself.

**Comment by AloisMahdal** [comment]
I'm confused a bit; I thought you were going to implement my suggestion but what you described in your last comment is not what I meant.  OK, I can deal with it, no problem.  But just to rule out misunderstanding:

The way I always understood and used the "toggling" behavior pattern is to enable user to make a "quick peek" into the main window to decide whether further action is needed.  (In that sense your patch is not even a compromise since it does not enable this workflow. Neither window manager will, the close widget is often far away from the tray--or even unavailable, as in case of i3; where I have to use keyboard shortcut).  The pattern makes a lot of sense with applications I've mentioned (or with most application that 'sit in tray') and I think it makes a lot of sense with QTS. 

That said, I understand if you just don't want to follow that pattern; it's your decision to make; I'll deal with that and still appreciate QST nonetheless .:)
