### ISSUE TITLE
Compile-time default syncthing (and inotify) paths?

### ISSUE THREAD

**Issue by vext01** [sieren/QSyncthingTray#155]
Hi,

It would be useful for packagers if there could be a compile-time switch to specify a syncthing (and inotify) binary path.

E.g.

For OpenBSD, I would like the syncthing path (for launching) to default to /usr/local/bin/syncthing.

Maybe something like: `cmake -DSYNCTHING_PATH=...`?

Thanks

**Comment by sieren** [comment]
I'd rather not take away the specification of a runtime path, but could think of supplying default paths for platforms.

**Comment by vext01** [comment]
Sounds good.

**Comment by sieren** [comment]
Adressed in https://github.com/sieren/QSyncthingTray/pull/159
