### ISSUE TITLE
Open Syncthing –> Not Authorized

### ISSUE THREAD

**Issue by heyjohannes** [sieren/QSyncthingTray#161]
I'm using QSyncthingTray on a mac (OSX 10.10) and when I try to open Syncthing with the command from QSyncthingTray it shows the message "Not Authorized" in a new window.

I've tried different API keys with no success.
I've tried to reinstall QSyncthingTray with no success.

Also QSyncthingTray is not showing any of my shared folders in the context menu.
Don't know if this is related to the issue described above.

Any tips about how to solve this? Thanks!

**Comment by sieren** [comment]
Have you ticked "Authentication" and entered your credentials? (To verify, login through the browser with the same credentials).

**Comment by heyjohannes** [comment]
Thanks for your quick tip.
Yes, I've ticked "Authentication" and entered my credentials. Still no success.

**Comment by sieren** [comment]
And I asume you made sure they are actually right in a web browser? 
I just tried to reproduce on my setup (same system) but it's working. 
Whats your Syncthing version?

**Comment by heyjohannes** [comment]
Yes, I made they are right.
Syncthing version is 0.14.5

**Comment by sieren** [comment]
Which QST version are you using?

**Comment by heyjohannes** [comment]
QST 0.5.2

**Comment by sieren** [comment]
Please make sure to close and re-open the Web View when changing credentials. Right now this doesnt trigger a refresh.

**Comment by heyjohannes** [comment]
Okay, I've tried this with new credentials. Still no success

**Comment by spookey** [comment]
Hello.
I was experiencing exact the same issue here.
Running ``syncthing v0.14.6``  and ``QSyncthingTray v0.5.2``  (both installed via homebrew) on OS X 10.11.6.

If no GUI Username & Password are configured in Syncthing, opening the WebView works fine.

I tried several Username & Passwords combinations (copy-pasting them to prevent typing mistakes), completely closing QST and restarting the Syncthing Daemon (via ``brew services restart syncthing``) afterwards - no luck 😿 

Then, I unticked the ``Use HTTPS for GUI`` checkbox - now it works 😻

**Comment by sieren** [comment]
Sweet! Thanks, thats good information. I'll have a look!

**Comment by sieren** [comment]
Just a follow up, before you unticked `Use HTTPS for GUI`, was the URL in QST specified with `https://..` too?

**Comment by spookey** [comment]
No. The URL I was using all the time was ``http://localhost:8384``

Should I test all the same again with some ``https://`` URL?

**Comment by spookey** [comment]
So, now I had the time to test this.

I set in QST the URL to ``https://localhost:8384`` and ticked the ``Use HTTPS for GUI`` checkbox in Syncthing.

Restarting both Syncthing and QST -> now opening the WebView works fine, too.

**Comment by sieren** [comment]
Hey everyone,

alright, thanks to @spookey I found out what the underlying issue was.
Apparently the HTTP Status Code in Syncthing changed slightly.

Previously you should have gotten an error/warning message if you mistakenly used `http` despite having set Syncthing to use `https`.

This has been changed now and adressed in https://github.com/sieren/QSyncthingTray/issues/164.

Will go into the next update.
