### ISSUE TITLE
Reduce compile-time memory usage

### ISSUE THREAD

**Issue by sieren** [sieren/QSyncthingTray#162]
Reduce compile-time memory usage by separating out the animated gifs into different `qrc` files.
https://github.com/sieren/QSyncthingTray/issues/157#issuecomment-245553565

**Comment by vext01** [comment]
Thanks for this.

**Comment by sieren** [comment]
ping @vext01 - I moved those files into separate QRC files. I hope this reduces compile time memory usage. Mind giving it a shot?

**Comment by sieren** [comment]
Any update before I close this?

**Comment by mulander** [comment]
@sieren hi, sorry for not getting back earlier. I'll test this in an hour or so.

**Comment by mulander** [comment]
I just re-tested the version we tried in September (v0.5.2) and did a fresh test of v0.5.5rc1 just now.

v0.5.2:
 Killed by the operating system for exceeding memory quota which is 1536 M.

v0.5.5rc1:
 Build successfully and the `peak` memory usage observed via top was ~700 M. That peak happened twice and lasted for less than 3 seconds, most of the build hovers between 300-400 M of RES memory.

Obviously there are more changes than just the GIF being moved out in the version I tested so I can't guarantee that this change has been the exact fix.

All in all I consider this fixed.

**Comment by sieren** [comment]
@mulander thanks for testing. Yeah, I'm quite sure this is responsible for the fix though as I experienced similar issues on AppVeyor before with MSVC running out of memory on the QRC files containing the gifs. This hasnt happened since either.
