### ISSUE TITLE
syncthing-inotify error on Mac

### ISSUE THREAD

**Issue by malaybasu** [sieren/QSyncthingTray#169]
Seems `qsyncthingtray` cannot find `syncthing-inotify`. If using the browse option, it shows a popup `inotify not found`. It does not launch `syncthing-inotify`  either.

**Comment by sieren** [comment]
Can you give me some more details like QST's version and platform?

**Comment by sieren** [comment]
Nevermind, was able to reproduce.

**Comment by sieren** [comment]
Deployed a fix for the next release.
