### ISSUE TITLE
Win7 x64: Tray Icon Not Working

### ISSUE THREAD

**Issue by meztup** [sieren/QSyncthingTray#178]
On Windows 7 x64 with QST 0.5.5, the tray icon doesn't animate upon activity, doesn't provide notifications, and doesn't respond to checking/unchecking the monochrome icon option in the settings. The plot window works and DOES show activity.

**Comment by sieren** [comment]
Hey @meztup 

Finally had the time to investigate this and found a couple of issues along the line.
Notifications however did work on my end (Windows 10).

Can you try out this version and give me feedback? 
https://github.com/sieren/QSyncthingTray/releases/tag/0.5.6

If all is well, I'd switch this from pre-release to release.

**Comment by meztup** [comment]
Everything seems to be working fine! I'll keep it running and let you know if this issue re-occurs. Thanks!
