### ISSUE TITLE
webkit version broken

### ISSUE THREAD

**Issue by poelzi** [sieren/QSyncthingTray#185]
As #147 is not added, webkit version broke.

`
[ 33%] Building CXX object CMakeFiles/QSyncthingTray.dir/sources/qst/syncconnector.cpp.o
/usr/src/build/QSyncthingTray/sources/qst/syncconnector.cpp: In member function ‘void qst::connector::SyncConnector::showWebView()’:
/usr/src/build/QSyncthingTray/sources/qst/syncconnector.cpp:110:36: error: no matching function for call to ‘qst::webview::SyncWebKitView::SyncWebKitView(QUrl&, std::pair<QString, QString>&, std::shared_ptr<qst::settings::AppSettings>&)’
      mAuthentication, mpAppSettings));
                                    ^
In file included from /usr/src/build/QSyncthingTray/includes/qst/webview.h:22:0,
                 from /usr/src/build/QSyncthingTray/includes/qst/syncconnector.h:40,
                 from /usr/src/build/QSyncthingTray/sources/qst/syncconnector.cpp:19:
/usr/src/build/QSyncthingTray/includes/qst/syncwebkitview.h:57:3: note: candidate: qst::webview::SyncWebKitView::SyncWebKitView(const QUrl&, const Authentication&)
   SyncWebKitView(const QUrl &url, const Authentication &authInfo);
   ^
/usr/src/build/QSyncthingTray/includes/qst/syncwebkitview.h:57:3: note:   candidate expects 2 arguments, 3 provided
/usr/src/build/QSyncthingTray/includes/qst/syncwebkitview.h:56:3: note: candidate: qst::webview::SyncWebKitView::SyncWebKitView()
   SyncWebKitView() = default;
   ^
/usr/src/build/QSyncthingTray/includes/qst/syncwebkitview.h:56:3: note:   candidate expects 0 arguments, 3 provided
CMakeFiles/QSyncthingTray.dir/build.make:248: recipe for target 'CMakeFiles/QSyncthingTray.dir/sources/qst/syncconnector.cpp.o' failed
make[2]: *** [CMakeFiles/QSyncthingTray.dir/sources/qst/syncconnector.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/QSyncthingTray.dir/all' failed
make[1]: *** [CMakeFiles/QSyncthingTray.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

`

`[poelzi@horas QSyncthingTray (744ef0f)]$ git bisect good
21990db245f4027f7d1a56f83c8c6fefbc0916ac is the first bad commit
commit 21990db245f4027f7d1a56f83c8c6fefbc0916ac
Author: sieren <matthias@s-r-n.de>
Date:   Sat Nov 26 21:24:49 2016 +0100

    Move Settings intos separate class
    
    Move Settings into a separate class.
    This step is a preparation for a refactoring of other classes,
    so each class can register to signals from settings.
    Thus we can remove the onUpdateSettings functions being
    called from Window.

:040000 040000 41b86ed3a3e5a46f8c8a5b09e9d44bd277f1b8ba f8b20c9953711daa629b8b362c392f7217d2c5d1 M      includes
:040000 040000 9c79e59ea71037dc375158e97eb72c53ae2a83dc b5da9385ea821a3ec64a8cfef55d1c848f4be6be M      sources
`

**Comment by sieren** [comment]
Ah, damnit!
Pushed a fix to master, can you try again?
