### ISSUE TITLE
travis-ci: re-enable linux build

### ISSUE THREAD

**Issue by marco-m** [sieren/QSyncthingTray#192]
Hello,

in the travis configuration file the linux part is commented out, so the only OS that builds is OS X. Are there specific problems? I might have some time to work on it.

**Comment by sieren** [comment]
Looking at the commit history this was because LLVM had taken down Travis CI support (due to traffic). Not sure if that's been changed by now, I'm sure it has. Somehow lost track of this :) I'd absolutely appreciate if you are gonna switch them on again.

**Comment by sieren** [comment]
Just if you're up for it and if it isnt too much additional work: https://github.com/sieren/QSyncthingTray/issues/147

Else I'm gonna do this in a couple of weeks anyway.

**Comment by marco-m** [comment]
FYI I am having some fun with travis and github outage :-)
