### ISSUE TITLE
Win x64: QST won't execute

### ISSUE THREAD

**Issue by meztup** [sieren/QSyncthingTray#199]
QST v0.5.7 won't start. Also, the download filename (and folder in the archive) shows the wrong version number, so perhaps there is a problem with the build...

**Comment by sieren** [comment]
Ah damn! Uploaded a new package. Might checking whether it works on your end now?

**Comment by meztup** [comment]
Works great! Thank you (yet again) for this project!

**Comment by sieren** [comment]
Thank you for making me aware of my screw up ;)
