### ISSUE TITLE
QST does not save iNotify path in preferences 

### ISSUE THREAD

**Issue by gadric** [sieren/QSyncthingTray#205]
I just reinstall my PC and upgraded to Windows 10. Syncthing version 14.23, syncthing-inotify version 0.8.5., QST version 0.5.7, all x64. Everything works fine but the inotify path settings in QST. Everytime I reboot my Computer, the field is empty again and QST does not start inotify. 

I've already restarted QST, but the problem persists. The setup was working on Windows 8.1. 

Is this an issue or do I just miss something?

**Comment by sieren** [comment]
I think I found the issue just by looking at the code.
Opened up a clean-up to do https://github.com/sieren/QSyncthingTray/issues/206 to squash these issues once and for all.

Will push a bugfix release asap.

**Comment by gadric** [comment]
thanks!

**Comment by sieren** [comment]
@gadric I took a stab at it this morning, do you mind giving this special build a test and giving me feedback?
https://dl.dropboxusercontent.com/u/2038446/QST_bugfix_test.zip

**Comment by gadric** [comment]
@sieren: thanks for your effort! I am still in a business trip but will be back home today evening. I will then and let you know!

**Comment by gadric** [comment]
Nice! It's working!

**Comment by sieren** [comment]
Sweet.. I'll merge this and then it'll officially be in the next version. Thanks for your report!

**Comment by daniele-orlando** [comment]
Same issue on MacOS here.
