### ISSUE TITLE
Linux compilation using qmake

### ISSUE THREAD

**Issue by 00cpxxx** [sieren/QSyncthingTray#208]
Hi, are the (brief) instructions for Linux related to qmake correct?

cd ./src  
./build_linux.sh  
./QSyncthingTray

There is no src folder, there is no build_linux.sh. There is a source folder but still no build script. Can you please update the instructions on building with qmake?

Checked latest version 0.5.7. and git tree.

**Comment by sieren** [comment]
Hey,

`qmake` support has recently been phased out as part of https://github.com/sieren/QSyncthingTray/pull/194/commits/cce478b99c01a2ed73e7c280ad78f3f834dcff60 and https://github.com/sieren/QSyncthingTray/pull/204

is there any particular reason you rely on `qmake` and not `cmake` ?

But thanks for pointing out the README isnt up to date.

**Comment by 00cpxxx** [comment]
cmake was failing so I tried qmake. In the end there were some missing libraries required. I installed then and qmake inside the source dir worked fine so I thought it would be useful to report.

Nothing to fix, just remove the qmake stuff from the readme then. Thanks.
