### ISSUE TITLE
feature request: monochrome icon

### ISSUE THREAD

**Issue by darrinholst** [sieren/QSyncthingTray#21]
Would it be possible to provide an option for a monochrome icon? It's nit picky, but it kind of stands out next to everything else in my menubar.

**Comment by sieren** [comment]
Good idea, I'll look into it. Certainly possible :+1:

**Comment by sieren** [comment]
Which color scheme would be appropiate? Full on black/white or greyscale?

**Comment by sieren** [comment]
![preview](https://cloud.githubusercontent.com/assets/5174440/11723639/b80d227c-9f6f-11e5-9629-a126874f1be6.jpg)
Would this combination work for you?

**Comment by darrinholst** [comment]
Looks fine to me. Thanks.

**Comment by sieren** [comment]
Added to master. Will be in the next build!
