### ISSUE TITLE
127.0.0.1 refuse to connect

### ISSUE THREAD

**Issue by dipenpatel235** [sieren/QSyncthingTray#213]
i have downloaded that 32 bit windows and then clicked on QSyncthingTray.exe but getting below error

127.0.0.1 refuse to connect

**Comment by sieren** [comment]
Have you installed and downloaded Syncthing? Is it running?

**Comment by dipenpatel235** [comment]
yes,,,,downloaded Syncthing and started Syncthing also.
yes..it is running on browser and worked.

now working fine.
thanks
