### ISSUE TITLE
qcustomplot.h changes the binary licence

### ISSUE THREAD

**Issue by XRevan86** [sieren/QSyncthingTray#215]
includes/contrib/qcustomplot.h is licensed under GPLv3+ which is also the licence of the resulting compiled binary as it is linked in.
Please, add a COPYING file for GPLv3+.

**Comment by mfk-ableton** [comment]
Will do when I get back to it. If you have some time in the meantime, feel free to do a PR for this :)

**Comment by sieren** [comment]
Will do when I have some time to get back to this. In the meantime, if you have some time, feel free to open a PR :)
