### ISSUE TITLE
0.5.8 executable broken on OSX

### ISSUE THREAD

**Issue by AlexKucera** [sieren/QSyncthingTray#218]
Sorry to report that the Mac app seems to be broken. The icon comes up as the broken app icon and it also does not start. No error or warning. It just doesn't start. A failed build process maybe?

**Comment by sieren** [comment]
I've just tried to reproduce this downloading the newest .dmg from Releases on 10.12.4 and it shows up normal.
Does it already appear broken within the .dmg ?

**Comment by AlexKucera** [comment]
Yep, it already seems to be broken within the DMG. I just downloaded it again.
![](http://babylondreams.de/shared/Screen-Shot-2017-07-10-at-09.45.05-hSCl/Screen-Shot-2017-07-10-at-09.45.05.png)

**Comment by sieren** [comment]
It looks like you're using an older OSX version, can you tell me which one? 
There's been a few changes to the build scripts recently, potentially somehow the target got moved up.

**Comment by AlexKucera** [comment]
Ah. That might be it. I am using 10.11.6

**Comment by sieren** [comment]
Ah right, yeah that seems likely.
I'll try to fix it tonight and push out another update.

**Comment by AlexKucera** [comment]
Appreciated. Thanks Matt.

**Comment by sieren** [comment]
Updated the .dmg in the release, please have a look and let me know if this fixes it.

**Comment by AlexKucera** [comment]
Thanks. Works perfectly now.
