### ISSUE TITLE
macOS: "Notifications" pref not saved across launches

### ISSUE THREAD

**Issue by brian-c** [sieren/QSyncthingTray#222]
This happens in 0.5.8, on two separate machines running 10.12.6:

- Open preferences, uncheck "Notifications". Quit QSyncthingTray.

- Relaunch QSyncthingTray. "Syncthing is running" notification pops up.

- Open preferences, notice "Notifications" is checked

**Comment by sieren** [comment]
Thanks, was able to reproduce this. Seems like something slipped during a refactoring.
Created a fix for this.

**Comment by brian-c** [comment]
Awesome, huge thanks!
