### ISSUE TITLE
Add a settings to open the Web Gui in the default browser and make qt5-webengine an optional dependency

### ISSUE THREAD

**Issue by doronbehar** [sieren/QSyncthingTray#224]
First of all, this is a wonderful piece of software you made here, very user friendly with great user interface. Well done.

The title of is perhaps a bit too long but I hope it's informative.

I noticed that (at least on Arch Linux), the package [`qt5-webengine`](https://www.archlinux.org/packages/extra/x86_64/qt5-webengine/) is pretty heavy and I guess that it is only needed to launch the GUI on it's separate window. I think that many users would like to be using their standard browser and many of us would like to see one package less as a dependency, or perhaps only as an optional dependency.

What do you think?

**Comment by sieren** [comment]
Sounds like a good idea :)

I just put in a PR that adds a new compiler flag to use a dummy class that does nothing other than call the system browser with a URL.

**Comment by doronbehar** [comment]
Looks good :)
Do you think it could be possible to make the software launch the GUI in it's separate window (with `qt5-webengine`) only when it is available? Meaning that during startup it would have to check so and decide whether it is possible to use `qt`'s web-engine?
This way it wouldn't be hard for distributors/packagers to decide whether to set that particular compilation flag or not.

**Comment by sieren** [comment]
I think that'd complicate things a lot (especially because QST is cross platform and used in a variety of package managers as well). I've personally never had to handle the scenario of multiple dynamic libraries across platforms. I'd be happy to look into it but don't quite know where to start.

I suppose those who provide packages to distributions could introduce a `lite` version of QST.

**Comment by doronbehar** [comment]
Hmm, that seems like a reasonable thing to do in the meantime. Thanks.
