### ISSUE TITLE
Saving notifications setting between reboots

### ISSUE THREAD

**Issue by es20490446e** [sieren/QSyncthingTray#238]
https://youtu.be/OmSdeB54q6M

**Comment by emanuele-f** [comment]
It is bugged. Workaround: edit `~/.config/QSyncthingTray/qst.con` and set `notificationsEnabled=false`

**Comment by sieren** [comment]
Would be nice if someone got do a PR and fix this, unfortunately I do not have the time right now to keep on maintaining this.

**Comment by es20490446e** [comment]
Many thanks 👍
