### ISSUE TITLE
New minor release

### ISSUE THREAD

**Issue by derlaft** [sieren/QSyncthingTray#239]
There seems to be many new features implemented (like autostart ability), but the last version was released a long time ago. 

Please consider making a new release so people can enjoy this features.

Requested by me and @es20490446e from AUR (https://aur.archlinux.org/packages/qsyncthingtray/)

**Comment by es20490446e** [comment]
Or forget about releases, and deploy continuously.

**Comment by es20490446e** [comment]
I have just published a [git package](https://aur.archlinux.org/packages/qsyncthingtray-git/).

**Comment by derlaft** [comment]
It seems the project is dead anyways

**Comment by es20490446e** [comment]
And it has memory leaks.

What I'm using right now is: syncthing-gtk-python3
