### ISSUE TITLE
Invalid/Unchecked dependency on qtwebengine

### ISSUE THREAD

**Issue by jklmnn** [sieren/QSyncthingTray#241]
When configuring with `-DQST_BUILD_NATIVEBROWSER=1` and not having `qtwebengine5-dev` installed the build fails with
```
fatal error: QtWebEngineWidgets/QWebEnginePage: No such file or directory
 #include <QtWebEngineWidgets/QWebEnginePage>
```
I would expect the build to not depend on this as I wanted to build with native browser support. If it still depends on this I would expect cmake to check that.

**Comment by yan12125** [comment]
My pull request https://github.com/sieren/QSyncthingTray/pull/240 should fix it.

**Comment by sieren** [comment]
Thanks @yan12125 - I merged https://github.com/sieren/QSyncthingTray/pull/240
