### ISSUE TITLE
Qsyncthingtray on OS X, “connection refused”

### ISSUE THREAD

**Issue by nullpointoh** [sieren/QSyncthingTray#30]
Hi,

I was previously using syncthing-bar, but moved over to QSyncthingTray, but the icon stays grey and I can't access the GUI (either from the menu or in a browser address bar.

I've tried using both the 127.x.x.x address and localhost, but neither work. I've deleted the old app completely from my laptop and was going to set up the folders again in the settings.

Hopefully someone knows the issue! I'm writing a story for a DJ technology site about how to set up syncing your music library over multiple computers.

**Comment by sieren** [comment]
Did you download syncthing itself ?
You need to install syncthing from https://syncthing.net/ and point QSyncThingTray to the 'syncthing' (or 'syncthing.exe' in windows) file.
It will then launch syncthing and take care of the rest.

I have an auto-downloader/installer in mind for a future release but given that it should work on all platforms i need some more time to get it done.

Let me know how it goes.

**Comment by nullpointoh** [comment]
Thanks for the response! I've got the latest version installed and pointed QSyncthingTray successfully to it. It says it's running. 
![screen shot 2015-12-17 at 14 43 25](https://cloud.githubusercontent.com/assets/16337081/11872323/8bcaaa88-a4cc-11e5-925d-5e8b9c096606.jpg)

**Comment by sieren** [comment]
Try using https instead of http if you use authentication 

-----
Sent & typed with clumsy thumbs

**Comment by nullpointoh** [comment]
No luck. I tried running the server on its own and came up with the security app blocker which I sorted. Now, the log has this issue:
[6TCGH] 15:33:49 FATAL: Cannot start GUI: listen tcp: lookup lcalhost: no such host
[monitor] 15:33:49 INFO: Syncthing exited: exit status 1
[monitor] 15:33:50 WARNING: 4 restarts in 7.922493565s; not retrying further

For some reason it has the wrong name for the GUI web page. I reset it on the CLI, added HTTPS and a login and it seems to be working now. I guess the settings are not in the main Syncthing folder, so deleting didn't reset.

Thanks for your help. I think you can close this issue now?

**Comment by sieren** [comment]
Interesting, can you confirm the issue has been within Syncthing then? (Depending on your OS Syncthing settings are stored somewhere outside - given you mean Syncthing itself, QSyncThing definitely stores its settings somewhere else in the OS, depending on which it is)

**Comment by nullpointoh** [comment]
Yeah, it was Syncthing actual that caused it. Once I renamed the web GUI
address it was fine.

Cheers!

On 17 December 2015 at 15:58, Matt Sieren <notifications@github.com> wrote:

> Interesting, can you confirm the issue has been within Syncthing then?
> (Depending on your OS Syncthing settings are stored somewhere outside -
> given you mean Syncthing itself, QSyncThing definitely stores its settings
> somewhere else in the OS, depending on which it is)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sieren/QSyncthingTray/issues/30#issuecomment-165493325>
> .
>



-- 
talk: twitter.com/happydan
read: www.presstojump.com | www.djworx.com
listen: mixcloud.com/happydan

**Comment by mfk-ableton** [comment]
Ok cool :) Glad you got it sorted. I guess we can close this then :)

**Comment by sieren** [comment]
Ok cool :) Glad you got it sorted. I guess we can close this then :)
