### ISSUE TITLE
QSyncthingtray on Windows 10, “unable to init SSL context:”

### ISSUE THREAD

**Issue by nullpointoh** [sieren/QSyncthingTray#34]
Hi again!

Now that I've got QSyncthingTray running smoothly on my Mac, I decided to switch over from SyncTrayzor for continuity on Windows. I've got SSL and a password enabled. QSyncthingTray works if I leave out the HTTPS (ie HTTP://LOCALHOST:8384) but the server GUI doesn't open. If I add HTTPS, I get the error in the title. I can open the server GUI in a browser, but get a security warning about the certificate.

**Comment by sieren** [comment]
Thanks, I'll look into it later today and post a fix/update. Quite frankly haven't tested SSL on Windows yet.
Which Windows version are you running?

**Comment by nullpointoh** [comment]
Windows 10

**Comment by nullpointoh** [comment]
Also, another small thing I noticed on the OS X GUI wrapper, on El Capitan: Check boxes don't appear in the settings.

**Comment by sieren** [comment]
Thanks. It's actually a known Qt bug: https://bugreports.qt.io/browse/QTBUG-43070
I pushed and verified the workaround discussed there.

**Comment by sieren** [comment]
As for the SSL Errors, apparently you need OpenSSL on Windows.
Simply installing Win64OpenSSL (for 64 Bit Windows) and then restarting QSyncthingTray should be sufficient:
http://slproweb.com/products/Win32OpenSSL.html

Can you drop me a line if that worked? Did on my end. Will have a look whether I can distribute the DLLs with the next release.

**Comment by nullpointoh** [comment]
That solved it, but it'd be much, much better for the UX if it can be part of the install. Did I read somewhere you plan on doing an installer?

**Comment by sieren** [comment]
I'd rather someone else would take care of that.
I agree on the UX Part, however with libraries such as OpenSSL there are certain laws in place which is why they arent bundled with Qt in the first place.
I will now display a message with a link to the website in case someone tries to access a https URL and doesnt have the DLLs installed.

**Comment by nullpointoh** [comment]
Not ideal, but would be a big help!
