### ISSUE TITLE
Feature request: show icon in application switcher when active

### ISSUE THREAD

**Issue by nullpointoh** [sieren/QSyncthingTray#35]
If you've got either the QSyncthingTray preferences or the GUI wrapper open on OS X, an application icon should appear in the CMD+TAB application switcher so you can switch to it. At the moment, you have to go to Mission Control to access the windows.

**Comment by sieren** [comment]
Done :+1: 
Will be in the next binary release.

**Comment by sieren** [comment]
https://github.com/sieren/QSyncthingTray/releases/tag/0.2.8
