### ISSUE TITLE
Recently changed files in menu

### ISSUE THREAD

**Issue by sieren** [sieren/QSyncthingTray#41]
Should display recently changed files in the menu.
Either per folder (click on Folder -> Recently changed files + option to open folder?)
or globally (ie dropbox-style)

**Comment by nullpointoh** [comment]
More importantly (for me, at least) would be some indicator for activity. Either binary or showing the traffic speed.

**Comment by sieren** [comment]
Already done today in https://github.com/sieren/QSyncthingTray/issues/40 and https://github.com/sieren/QSyncthingTray/issues/38

Hope to push out a new release later today or tomorrow.

**Comment by sieren** [comment]
@nullpointoh I have a UX question for you :) When you click on a recently changes file, would you expect the app to open the file or the containing folder?

**Comment by nullpointoh** [comment]
Definitely folder. There's a chance the file could be without an app
associated.

**Comment by sieren** [comment]
Good point! Thanks

**Comment by sieren** [comment]
Alright. Pretty much done.
Recently deleted files are shown, too, albeit greyed out.
New files can be clicked and the Finder opens the parent folder.

Need to verify https://github.com/sieren/QSyncthingTray/commit/f86f762890d8c756def882ebf48b1f289f86781c on Windows and Ubuntu tomorrow before I'll merge and make a new release with all the new features.
