### ISSUE TITLE
"New Version" Notification

### ISSUE THREAD

**Issue by sieren** [sieren/QSyncthingTray#42]
Since there's no auto-updater for all platforms implemented right now, a preliminary check for a new version of QSyncthingTray with a notification would be nice (which ultimately leads to the download page).

Alternatively implement Sparkle Framework for Mac Platform and ?? for Windows.

**Comment by Strayer** [comment]
A simple way of just notifying of a new version would probably be the releases API:
https://api.github.com/repos/sieren/QSyncthingTray/releases/latest

The application could simply compare the tag_name to a built-in tag_name and show a notification if it differs, maybe even show a simple dialog with the actual release notes on notification click.

The [API terms](https://help.github.com/articles/github-terms-of-service/#b-api-terms) only state:

> Abuse or excessively frequent requests to GitHub via the API may result in the temporary or permanent suspension of your account's access to the API. GitHub, in its sole discretion, will determine abuse or excessive usage of the API. GitHub will make a reasonable attempt via email to warn the account owner prior to suspension.

Not sure what to think of this. I guess a daily update check is not excessive? Maybe someone else has experience with this.

**Comment by sieren** [comment]
Cool. Thanks for the pointer.
Might as well just query the API on a weekly basis and then redirect the user to a download page.

**Comment by MoOx** [comment]
This solution is better than nothing indeed :)

**Comment by sieren** [comment]
Not sure what to do about Linux users though who compile from source or get a qst from some other source. Might as well make this platform-dependant for Mac and OSX first and see how it goes.

**Comment by sieren** [comment]
Alright, took some time to take care of this. There's a PR in place now and this will make it into the next version.
