### ISSUE TITLE
Move to QWebEngine

### ISSUE THREAD

**Issue by sieren** [sieren/QSyncthingTray#55]
QWebKit is marked deprecated, thus this project should move to QWebEngine for all things Syncthing-UI.

**Comment by kirichkov** [comment]
Resolving this issue will most probably fix the following bug:
Whenever I use QSyncthingTray to view the Syncthing web UI, checkboxes do not appear:
![qsyncthingtray](https://cloud.githubusercontent.com/assets/209263/12114929/c27b99fe-b3b6-11e5-9923-d6993b28ee3f.png)

Resizing has no effect on showing the checkboxes

They appear just fine when using Safari to view the UI:
![syncthing web](https://cloud.githubusercontent.com/assets/209263/12114930/c2a12606-b3b6-11e5-999e-34783d17d711.png)

**Comment by sieren** [comment]
@kirichkov interesting. I thought this was fixed in https://github.com/sieren/QSyncthingTray/commit/4821f4486f004a6bfe59af7be68c882da22e6e8d .. are you using the most recent release? 
Other than that, you're right... this will probably resolve itself once the transition is done.

**Comment by kirichkov** [comment]
My bad! No! I'm using 0.2.7 which I installed, yesterday via homebrew cask. Apparently it is not using the most recent version. I'll open an issue with homebrew.

**Comment by sieren** [comment]
:+1: thanks.
Down the road I'll probably include frameworks to check for updates for Mac/Win versions... Doing that on a different project with the same structure as this one as of now so shouldnt be too much work and make things a lot easier.

**Comment by kirichkov** [comment]
Just FYI my pull request was accepted so homebrew is now pointing to 0.3.0

**Comment by sieren** [comment]
Cool! Thank you :)
