### ISSUE TITLE
Question: Does quitting QSyncthingTray shut down the Syncthing server?

### ISSUE THREAD

**Issue by nullpointoh** [sieren/QSyncthingTray#56]
Just wondering if you have to kill the server before quitting? Might be worth having QSyncthingTray shut everything down on exit.

**Comment by sieren** [comment]
Yeah, that should happen (see https://github.com/sieren/QSyncthingTray/blob/master/src/syncconnector.cpp#L467 )

**Comment by nullpointoh** [comment]
Cool Whip. Nearly finished my guide. It's for djworx.com, FYI.

**Comment by sieren** [comment]
Cool! Hit me up with a link when its finished :)

**Comment by nullpointoh** [comment]
I've followed you on Twitter (@happydan) so will send on there, if that's cool? Might be a few weeks before it goes live as there's a bit of a backlog.

**Comment by sieren** [comment]
Cool! Sounds good :+1:
