### ISSUE TITLE
Win x64: Steadily Increasing Memory Usage

### ISSUE THREAD

**Issue by meztup** [sieren/QSyncthingTray#57]
Maybe a non-issue, but on Windows x64 Ultimate SP1, noticed (via Process Explorer) private memory usage starting at 7580K and gradually increasing to 55920K in the space of exactly 4 hours. Upon opening the built-in web interface, this climbed instantly to 102236K and did not decrease after closing the web interface (although I only monitored it for 3 hours afterward.) During this test, I did not update any files on any local or remote syncthing folders. This "issue" did not seem to negatively impact the performance of QST or my machine.

**Comment by sieren** [comment]
Interesting, I deliberately decided against releasing the WebKit interface for performance reasons.I only did some initial measurements on Mac and saw an increase up to 70mb....
We can leave this open for now to compare it with the WebEngine version which I'll hopefully do this week.

**Comment by sieren** [comment]
Adressed in branch which moves to QWebEngine.
