### ISSUE TITLE
Silent Fail When Protocol in Settings URL Is Incorrect

### ISSUE THREAD

**Issue by meztup** [sieren/QSyncthingTray#58]
When a user selects "Use HTTPS for GUI" in Syncthing settings, but fails to update the protocol within the URL in QSyncthingTray settings, QST shows "Status:Connected" but, in reality, cannot. Subsequently:
1) The check for SSL capabilities (and possible user notification) does not fire as designed.
2) QSyncthingTray cannot establish access to the Syncthing API.
3) If SSL capabilities aren't available, then the "Open Syncthing" feature will break.

**Comment by sieren** [comment]
Will do a string comparison with the URL and replace and occurences of http: with https:

**Comment by meztup** [comment]
Please note that I had initially made some assumptions about the issue that my further testing proved to be incorrect, and I updated this issue about an hour after initial creation. 

The issue is that if Syncthing is using https, and QSyncthingTray is not, it thinks everything is A-OK. I'm thinking this might be because Syncthing still responds over http://ip:port (although without useful information) even when it is in https mode.

You might have to change the URL validation in order to determine if the string manipulation needs to happen (unless there is an easier way to discover that Syncthing is using https).

**Comment by sieren** [comment]
I've addressed this by showing a warning when we encounter any SSL Errors and the URL is set to http://

Not the best of fixes, but it should do for now. Eventually I need to rewrite the connection handling altogether and come up with a better solution.
