### ISSUE TITLE
HiDPI support in the webview

### ISSUE THREAD

**Issue by nbrownus** [sieren/QSyncthingTray#59]
Would be great to support a scaling factor for the syncthing web view. Super tiny on hidpi screens.

**Comment by sieren** [comment]
Noticed that as well, quite sure it'll be fixed by https://github.com/sieren/QSyncthingTray/issues/55

**Comment by sieren** [comment]
Pushed a new release - can you verify whether this is working with QWebEngine?

**Comment by nbrownus** [comment]
It is still very tiny. Poking around the qt docs, maybe exposing http://doc.qt.io/qt-5/qwebenginepage.html#zoomFactor-prop
in the preferences would let me get it looking right?

**Comment by nbrownus** [comment]
Setting `QT_DEVICE_PIXEL_RATIO=2` environment variable actually scales the webview properly for me.

**Comment by sieren** [comment]
Cool.. I reopened this though because setting it from the UI might be helpful for users less experienced w/ settings Env Vars :+1:

**Comment by sieren** [comment]
Added in recent release:
https://github.com/sieren/QSyncthingTray/releases/tag/0.4.2b
