### ISSUE TITLE
Issue with SSL

### ISSUE THREAD

**Issue by jeanrjc** [sieren/QSyncthingTray#61]
On OSX 10.8.5, an QsyncthingTray from QsyncthingTray.dmg release 0.4

I have the `SSL Warning`:

>The SyncThing Server seems to have HTTPS activated, however you are using HTTP. Please make sure to use a correct URL.

And I can't access the WebUI interface from QST:

>The requested URL could not be retrieved

Although I can from my browser (Firefox)

Then, if I change the address to `https://127.0.0.1:8384/`

I don't have the `SSL Warning` but I'm still unable to open syncthing from QST with a different error:

>This webpage is not available

Although I can open it from Firefox.

I had no problem in the previous release.

As a side note, when I close the WebUI window, it also closes the preference window which I found annoying.

Thanks.

**Comment by sieren** [comment]
Thanks.
I was able to reproduce this. Will see if I can fix this tonight and push out a new release.

**Comment by sieren** [comment]
Pulled the 0.4 release for now.

**Comment by sieren** [comment]
I managed to identify 2 of the 3 bugs you reported and deployed fixes:
https://github.com/sieren/QSyncthingTray/releases/tag/0.4.1

I'm not quite sure whether this fixes displaying the website when run on HTTPS as I couldnt reproduce this issue on my end.
Do you mind reporting back how this works now?

**Comment by jeanrjc** [comment]
Hi
So the issue remains. Only the SSL error message disappears, but I have the same errors with the WebUI from QST (with https and http).

**Comment by jeanrjc** [comment]
Issues appear to be fixed on version 0.4.2 for OSX.
Thanks

**Comment by sieren** [comment]
Oh! Glad to hear! Thanks for reporting back
