### ISSUE TITLE
Win7 x64: QtWebEngine Loading Slow

### ISSUE THREAD

**Issue by meztup** [sieren/QSyncthingTray#64]
With QSyncthingTray 0.4.1 beta, "Open Syncthing" takes approx 4.5 minutes to load on Windows 7 x64 Ultimate.

*Note:*
A shot in the dark, but might be similar to [this issue](https://forum.qt.io/topic/49576/qtwebengine-extremely-slow-windows-7-vs2013-build) discussed on the Qt Forum.

**Comment by sieren** [comment]
Thanks for the link, that's helpful. I updated Qt to 5.5.1 and compiled QST against it, might wanna give it a try before I make an official release?
https://www.dropbox.com/s/klzsktishh1ycyt/QSyncthingTray_0.4.1b2_WIN64.zip?dl=0

**Comment by meztup** [comment]
Perfect--4.6 **seconds**!

**Comment by sieren** [comment]
Phew! That was easy :) Will go into the next official release, will leave this open till then.

**Comment by sieren** [comment]
Resolved in recent release:
https://github.com/sieren/QSyncthingTray/releases/tag/0.4.2b
