### ISSUE TITLE
Feature: Manually Start and Stop Syncthing

### ISSUE THREAD

**Issue by Christian308** [sieren/QSyncthingTray#65]
I like QSyncthingTray a lot and think it adds a lot of convenience to the user. The only thing missing for me is that I would like to be able to start and stop the underlying Syncthing from the icon/menu in the traybar. In Dropbox there is a menu item "Pause Syncing" for that purpose. This way the user is able to easily switch Syncthing off while e.g. tethering via the cell phone.    
Currently I configured QSyncthingTray to auto-pause when a certain process is running, so by starting an external program I achieve the desired effect. However, this is just a workaround as it is similar to starting and stopping Syncthing from the command line. I was wondering if you would consider to add a menu item to activate and deactivate the pause (start and stop Syncthing).
Thank you.

**Comment by sieren** [comment]
Great idea! :)
Will keep that on the radar and add it in a future version.

**Comment by sieren** [comment]
Added in recent release:
https://github.com/sieren/QSyncthingTray/releases/tag/0.4.2b
