### ISSUE TITLE
Windows: Syncthing not Shutting Down (+ Feature Request)

### ISSUE THREAD

**Issue by meztup** [sieren/QSyncthingTray#66]
Problem:

On Windows 7 x64 Ultimate, when using QST's "Launch Syncthing" option, the Syncthing process remains after shutting down QST. iNotify **does** close properly.

Feature Request:

Implement "graceful" shutdown by utilizing Syncthing API (rest/system/shutdown). This would probably need another option in QST settings for those that prefer to run Syncthing manually rather than having QST launch the executable for them.

Thoughts?

(Edit: For me, this issue exists in all the Win releases -- 0.2.6 to current)

**Comment by sieren** [comment]
Could be a bug, could also be because Syncthing might launch with an autorestart mode, so killing it will automatically respawn it. Either way, I'll investigate.

Agreed on the Feature request. It should shutdown gracefully either way. A few more options wouldnt harm though, manual launch is part of https://github.com/sieren/QSyncthingTray/issues/65 too.

**Comment by meztup** [comment]
This is still occurring with 0.4.2b. However, if I use the new "Pause Syncthing" option, both iNotify and the two Syncthing processes successfully shutdown.

(I'm not sure if commenting here will automatically re-open the issue or not...)

**Comment by sieren** [comment]
Hey,

I was able to reproduce this and came up with a new solution:
https://github.com/sieren/QSyncthingTray/releases/tag/0.4.2b2

Make sure to set the checkbox in Preferences, and let me know how it works out.

**Comment by meztup** [comment]
As long as Syncthing has not established a connection to another machine, it works. If it **has** established a connection, then one of the syncthing processes does not shut down. If I pause syncthing from QST, wait for the processes to close, and then unpause it, QST shuts down both syncthing processes on exit (regardless of whether a connection to another machine has been established.)

Pausing takes about 15 seconds to close the processes. Perhaps you are using the same method on quitting QST? Is there a fail-safe that says, "OK, this is taking way too long. I'll just shutdown the old way so that I'm not running forever"?

On a side note, this program is running very solidly on my machine and is performing beautifully.

**Comment by sieren** [comment]
I'm giving Syncthing a 10sec grace period in the recent update. Apparently thats not enough, I wonder though if dropping off the shutdown message and then leaving the processes by themselves after quitting Syncthing might be sufficient (thus not force-killing the process).

The failsafe is exactly in there as you say, however QST can only track the master process, not the child syncthing instances (which ive only seen on Windows anyway). I might bump up the grace period to 20 seconds in the next update and think about some other way of solving this in the meantime.

**Comment by meztup** [comment]
Dropping off the shutdown message and trusting Syncthing to close itself would probably work just fine. 

Increasing QST's grace period too much might cause issues if users try/need to re-open it before the previous instance is done counting (but not sure). The only other solution that I could see is a separate process whose only job is to handle and confirm shutdown--which might be overkill in this case.

**Comment by sieren** [comment]
Hey,

took some time to investigate this more thoroughly and found two potential bugs leading to the shutdown not being executed properly.

Mind testing the new version?
https://github.com/sieren/QSyncthingTray/releases/tag/0.4.2

**Comment by meztup** [comment]
Perfect! Much faster shutdown and **ALL** Syncthing processes closed--both with and without a connection established to another machine.

Again, thank you...

**Comment by sieren** [comment]
Yay! Glad to hear! Finally ;)
