### ISSUE TITLE
Feature(ish): Version Information

### ISSUE THREAD

**Issue by meztup** [sieren/QSyncthingTray#67]
While testing previous versions to compare with the current, I had some difficulty keeping track of which I had running. Adding some version information would be really helpful in the future (maybe on another tab?)

**Comment by sieren** [comment]
I agree... proper in-app versioning is on my radar.
I'm deploying a cross-plattform (win/mac) auto-updater on a different tool with a similar architecture which should be fairly easy to apply to QST down the road.
