### ISSUE TITLE
For future release could you use the full version number?

### ISSUE THREAD

**Issue by MoOx** [sieren/QSyncthingTray#78]
I saw that you used in the past things like "QSyncthingTray_0.3_MAC.dmg"

Would you be open to use full version (x.y.z) all the times "QSyncthingTray_0.3.0_MAC.dmg"?
This would help to update the cask recipe https://github.com/caskroom/homebrew-cask/blob/master/Casks/qsyncthingtray.rb#L5 more quickly
:)

Have a nice day!

Ref: https://github.com/caskroom/homebrew-cask/pull/17533/files

**Comment by sieren** [comment]
Oh yeah, sorry, will stick to this scheme... Thanks for making me aware.

**Comment by MoOx** [comment]
Thank you.
