### ISSUE TITLE
Wrong trancated non-latin file names in Last Synced Files menu 

### ISSUE THREAD

**Issue by zuf** [sieren/QSyncthingTray#79]
There an example.
![qsyncthingtray_menu_bug](https://cloud.githubusercontent.com/assets/105518/12810768/405f8f30-cb39-11e5-9c55-47a534224ed9.png)

**Comment by mfk-ableton** [comment]
Thanks... Will investigate. Probably needs work on the encoding. 
Just to get this right: you refer to the question mark appearing in the text right? Truncation is fixed-size.

**Comment by sieren** [comment]
Thanks... Will investigate. Probably needs work on the encoding. 
Just to get this right: you refer to the question mark appearing in the text right? Truncation is fixed-size.

**Comment by zuf** [comment]
Yes. This question-mark here because somewhere cyrillic unicode (usually 2 bytes per char in utf-8) char splitted incorrectly. May be because std:string conversion near here: https://github.com/sieren/QSyncthingTray/blob/b8899aa3b5379e764f8a1ad66dddf12e48cb0ea6/src/window.cpp#L578

Why not to use QString everywhere if you use Qt already? This can remove all kind of string issues like this.

**Comment by mfk-ableton** [comment]
Yeah, I will. This was my first Qt project ;-)

**Comment by sieren** [comment]
Yeah, I will. This was my first Qt project ;-)

**Comment by sieren** [comment]
Hey,

merged using QString to master. I'll leave this open for now and check back with you when I'm putting out a new release.

**Comment by sieren** [comment]
0.4.3 is out, please let me know if this resolves the issue.
