### ISSUE TITLE
Request: Define tray icon click behavior

### ISSUE THREAD

**Issue by colin-nerdery** [sieren/QSyncthingTray#80]
Not sure if that behavior makes sense across platforms, but currently clicking the QSyncthingTray icon doesn't do anything.

On a windows system, double-clicking a tray icon (most often) activates the application in some way. Opening the SyncThing browser probably makes the most sense here.

A single left click often opens the context menu (same behavior as right click) but I think apps are less consistent here.

Thoughts?

**Comment by sieren** [comment]
I guess that's an UX oversight of mine as the behaviour on Mac is different (essentially no double-clicks).
I'll tag it as an enhancement and will get it into the next version. Thanks for the suggestion.

**Comment by sieren** [comment]
Double Click will now open the web view.
Thanks for the report!
