### ISSUE TITLE
OS X:  precompiled binary does not open on a case-sensitive FS

### ISSUE THREAD

**Issue by frqnck** [sieren/QSyncthingTray#82]
The precompiled binary inside `QSyncthingTray_0.4.2_OSX.dmg` does not seem to work on a case-sensitive file system.

The error message is 
```
You can’t open the application “QSyncthingTray” because it may be damaged or incomplete.
```
It works fine if dragged to a non-case sensitive FS.

**Comment by sieren** [comment]
Can you try something for me?
Rightclick on the .app -> Show Package Contents then navigate to "Mac OS" and rename QSyncThingTray to QSyncthingTray

**Comment by frqnck** [comment]
Renaming the entry point in the MacOS folder fix the issue.

**Comment by sieren** [comment]
Thanks. Will fix this in the next release.

**Comment by frqnck** [comment]
Thanks to you for the work and efforts put into QSyncThingTray.
IMO, the best companion to Syncthing. Happy sunday.

**Comment by frqnck** [comment]
I suspect it is probably related to the same naming issue so i will file that here for now:

Notifications (under Preferences > Main > Appearance) keep on nagging when option is disabled (un-ticked). When restarting the app, it is always enable too.

**Comment by sieren** [comment]
They might indeed be related, can you verify whether other settings are being kept saved? (e.g. monochrome icon?)

**Comment by frqnck** [comment]
The other settings are working as expected and stick on app restart.

Only `Notifications` is playing up.

**Comment by sieren** [comment]
0.4.3 is out. I'll close this for now but if the notification bug is still appearing on your end, let me know in a new issue so I can track it for 0.4.4.
