### ISSUE TITLE
QSyncthingTray is convinced that syncthing is already running when it isn't

### ISSUE THREAD

**Issue by DarwinAwardWinner** [sieren/QSyncthingTray#87]
Recently I've started having an issue where starting QSyncthingTray doesn't start up syncthing along with it. When I go to the options, it tells me that syncthing is already running, but there is no syncthing process in the output of `pgrep syncthing`, and as expected, QSTray can't connect to syncthing and the web GUI doesn't work, since there's no process to connect to. Quitting and restarting QSTray doesn't help. It always says that syncthing is already running and refuses to start it. Manually starting syncthing from the command line does work, and QSTray can connect to it once it is started. It just refuses to start syncthing on its own.

I am on OSX 10.11.3. Syncthing and QSTray version info:
```
$ brew info syncthing syncthing-inotify
syncthing: stable 0.12.19 (bottled), HEAD
Open source continuous file synchronization application
https://syncthing.net/
/usr/local/Cellar/syncthing/0.12.19 (6 files, 13.1M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/syncthing.rb
==> Dependencies
Build: go ✘
==> Caveats
To have launchd start syncthing at login:
  ln -sfv /usr/local/opt/syncthing/*.plist ~/Library/LaunchAgents
Then to load syncthing now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.syncthing.plist

WARNING: launchctl will fail when run under tmux.

syncthing-inotify: stable 0.6.8 (bottled), HEAD
File watcher intended for use with Syncthing
https://github.com/syncthing/syncthing-inotify
/usr/local/Cellar/syncthing-inotify/0.6.8 (5 files, 6M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/syncthing-inotify.rb
==> Dependencies
Build: go ✘
==> Caveats
To have launchd start syncthing-inotify at login:
  ln -sfv /usr/local/opt/syncthing-inotify/*.plist ~/Library/LaunchAgents
Then to load syncthing-inotify now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.syncthing-inotify.plist

WARNING: launchctl will fail when run under tmux.
$ brew cask info qsyncthingtray
qsyncthingtray: 0.4.2
QSyncthingTray
https://github.com/sieren/QSyncthingTray
/opt/homebrew-cask/Caskroom/qsyncthingtray/0.4.2 (108 files, 133M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/qsyncthingtray.rb
==> Contents
  QSyncthingTray.app (app)
```

**Comment by sieren** [comment]
Hey,

thanks for the report.
I have a suspicion as to why this is. I'm assuming you have syncthing-inotify started. 
The process-detector might falsely detect it as syncthing and thus report it as already started.

Will fix this in the forthcoming release.

**Comment by DarwinAwardWinner** [comment]
I don't necessarily have syncthing-inotify already running, but I do have QSTray set to start it. Maybe if QSTray is multi-threaded, it's a race condition that is only triggered when thread A starts syncthing-inotify before thread B checks for syncthing running.

**Comment by sieren** [comment]
Note to self:
L76 in https://github.com/sieren/QSyncthingTray/blame/master/src/platforms/darwin/macUtils.hpp#L76
should be 

` cmd << "ps -ef | grep -w " << someapp << " | grep -v grep -c"; `

**Comment by sieren** [comment]
Yeah. That makes sense and is probably the root-cause.
I havent used syncthing-inotifier for a while - will test those conditions when I'm doing the fix.

**Comment by sieren** [comment]
I pushed a fix, do you mind verifying if this works on your end before I merge to master?

https://www.dropbox.com/s/spqnku28489u5eg/QSyncthingTray.dmg?dl=0

**Comment by DarwinAwardWinner** [comment]
Works like a charm.

**Comment by DarwinAwardWinner** [comment]
Thanks for the quick turnaround on this!

**Comment by sieren** [comment]
Sweet! Couldnt verify on my machine as it didnt occur at all, thanks for reporting back! :+1:
