### ISSUE TITLE
Port to Linux?

### ISSUE THREAD

**Issue by rodneyrod** [sieren/QSyncthingTray#9]
Since this is based on Qt, would it be possible to port this indicator tray to Linux?
It would be nice to have something like this for KDE and other Qt heavy DEs.

**Comment by sieren** [comment]
@rodneyrod definitely. I believe most of it should work out of the box anyway, given OS X and Linux are both POSIX-compliant.
I will keep that in mind and give it a shot on Debian soon.

**Comment by sieren** [comment]
@rodneyrod Gave it a shot on Linux and it almost worked out of the box.
Added a screenshot and some more detailed instructions. I hope I can release a binary next as well.  But any help is appreciated too ;-)
