### ISSUE TITLE
Typo in linux build of version 0.4.3

### ISSUE THREAD

**Issue by whorfin** [sieren/QSyncthingTray#90]
Got a stream of errors attempting "build_linux.sh", traced to src/platforms/linux/posixUtils.hpp

The below hack should point to the solution:

#if 0   // typo?
    template<typename U&&, typename T>
    void doubleClicked(T&& func, T ref)
#else
    template<typename U, typename T>
    void doubleClicked(U&& func, T ref)
#endif

**Comment by sieren** [comment]
Ah damnit! I pushed a fix 

I really need to do https://github.com/sieren/QSyncthingTray/issues/89 next to avoid those things.
