### ISSUE TITLE
OS X reports high energy consumption

### ISSUE THREAD

**Issue by ulfmaier** [sieren/QSyncthingTray#93]
I'm using v0.4.3 and OS X reports that the QSyncthingTray uses much energy. It's the first time i use QSyncthingTray, so i can't say if the problem existed on earlier releases.

Energy impact varies between 2,6 and 7,6.

OS X 10.11.3

![screen shot 2016-02-24 at 15 43 01](https://cloud.githubusercontent.com/assets/896240/13288917/4f00478e-db0e-11e5-9ed4-401e4f2393af.png)
![screen shot 2016-02-24 at 15 44 45](https://cloud.githubusercontent.com/assets/896240/13288918/4f154530-db0e-11e5-9e3c-bd93c979197e.png)

**Comment by sieren** [comment]
Thanks for the report. I suppose this is because due to increased polling of data from syncthing itself. I have plans to expose the polling interval to the user so it could be set to a more energy-friendly interval.
Will put this on the tab for next version.

**Comment by sieren** [comment]
I wonder whether this relates to the issue reported here: https://github.com/sieren/QSyncthingTray/issues/94

Can you try adding that key to the Info.plist just to verify if this goes away?

**Comment by ulfmaier** [comment]
Short answer ... yes it helps. No more energy consumption warning. Will add more details in some hours when the activity monitor has enough data for an average.

**Comment by sieren** [comment]
Cool! I'd have been surprised if the API polling was the cause of this issue.

**Comment by ulfmaier** [comment]
Ok it won't tell me an average ... so i'll guess ... but the exact numbers don't really matter.

The energy impact is now around 2.6 in average.
For comparison of this nothing saying number ... the energy impact of MEGAsync is 0.1, the Mail application i use has 0.5, Dropbox 0.25.
The energy impact of QSyncthingTray includes syncthing, because syncthing is launched by QSyncthingTray. The energy impact of syncthing is around 0.5 -> that makes ~2.1 for QSyncthingTray alone. Thats still a bit much for what it does.

If this does matter:
I have 4 shares ... each with a rescan interval of 60 sec. So nothing extreme.

Without the GPU correction i didn't use it while on battery ... it really made a noticeable difference in battery time. Now with the correction i think i won't care ... for me no more a big problem.

**Comment by sieren** [comment]
Thanks for the detailed report.
I agree, it's still too much. I'll leave this open for future investigation.

**Comment by sieren** [comment]
The next version will have a customisable polling interval setting that can be set to ask `syncthing` for information less frequently thus decreasing CPU impact. I'll do some profiling later on to see if this is a valid assumption, although I'm relatively sure based on previous observations.
