### ISSUE TITLE
OSX: Fix for supporting internal GPU

### ISSUE THREAD

**Issue by lolllpop** [sieren/QSyncthingTray#94]
As soon as QSyncthingTray is started, OSX switches to the discrete GPU which is much more resource hungry than the internal one. 

There is an easy fix working for me: just add the following to the Info.plist:
```
        <key>NSSupportsAutomaticGraphicsSwitching</key>
        <true/>
```

Some googling gave:
https://bugreports.qt.io/browse/QTCREATORBUG-11799
https://developer.apple.com/library/mac/qa/qa1734/_index.html

**Comment by sieren** [comment]
Thanks :) Will go into the next release
