### ISSUE TITLE
QSyncthingTray 0.4.4 OSX not starting/crashing

### ISSUE THREAD

**Issue by muellmaa** [sieren/QSyncthingTray#99]
i've tried out anything and version 0.4.4 just fails to start under OS X El Capitan 10.11.4... in activity monitor it shows as being crashed... 0.4.3 works perfect.

under OS X El Capitan 10.11.3 version 0.4.4 works too. so it must have something to do with the latest apple update :-S

thx

**Comment by sieren** [comment]
thanks for the report. i'll investigate and get a fix ready asap

**Comment by sieren** [comment]
Tried to reproduce but to no avail. Can you drop me a crashlog here?

**Comment by muellmaa** [comment]
hey thanks for your fast reply. I tried again and now it works! :-S I've no clue, why the app didn't start and 0.4.3 did :-S
